#!/usr/bin/env python3
"""Local (non-daemon) setup helpers: auth-key extraction and the collection job.

These do not touch the band session: `key` runs ADB to read the auth key out of
the Mi Fitness logs, and `schedule` registers the periodic collector with
Android's JobScheduler.
"""
import os
import shlex
import shutil
import subprocess
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

VENDOR_APPS = "com.xiaomi.wearable com.mi.health"
KEY_FILE = os.path.join(_ROOT, "notes", ".authkey")

JOB_ID = 8801
JOB_DIR = os.path.join(os.path.expanduser("~"), ".miband")
JOB_SCRIPT = os.path.join(JOB_DIR, "collect.sh")
JOB_LOG = os.path.join(JOB_DIR, "collect.log")


def _adb_path():
    """Resolve the ADB client: $MIBAND_ADB, adbwire on PATH, or the vendored one."""
    override = os.environ.get("MIBAND_ADB")
    if override:
        return override
    found = shutil.which("adbwire")
    if found:
        return found
    local = os.path.join(_ROOT, "tools", "adbwire", "out", "adbwire")
    if os.path.exists(local):
        return local
    raise ValueError("adbwire not found; run ./install.sh (or set MIBAND_ADB)")


def _adb(args):
    """Run adbwire (one shell command as the shell UID)."""
    return subprocess.run([_adb_path()] + args, capture_output=True, text=True)


def extract_key():
    """Recover the 32-hex Xiaomi auth key from Mi Fitness logs over ADB."""
    paths = " ".join(f"/sdcard/Android/data/{p}/files/log/*.log"
                     for p in VENDOR_APPS.split())
    pattern = "(encryptKey|token|authKey|huamiAuthKey)[\":= ]+[[:xdigit:]]{32}"
    cmd = (f"grep -rEho '{pattern}' {paths} 2>/dev/null "
           f"| grep -oE '[[:xdigit:]]{{32}}' | tail -1")
    out = _adb([cmd])
    if out.returncode != 0:
        detail = (out.stderr or out.stdout).strip().splitlines()
        raise ValueError("ADB failed: " + (detail[-1] if detail
                                           else f"exit {out.returncode}"))
    key = out.stdout.strip()
    if not key:
        raise ValueError("no auth key found in vendor logs "
                         "(is Mi Fitness still paired? do not unpair it)")
    return key


def save_key(key):
    os.makedirs(os.path.dirname(KEY_FILE), exist_ok=True)
    with open(KEY_FILE, "w") as fh:
        fh.write("0x" + key + "\n")
    os.chmod(KEY_FILE, 0o600)
    return KEY_FILE


def _need_scheduler():
    if not shutil.which("termux-job-scheduler"):
        raise ValueError(
            "termux-job-scheduler not found (install Termux:API and grant it)")


def _job_script_body():
    daemon = os.path.join(_ROOT, "bin", "mibandd")
    return (
        "#!/data/data/com.termux/files/usr/bin/bash\n"
        "# Generated by `mibandd schedule install` - do not edit.\n"
        "# Runs one activity collection; output is appended to the log.\n"
        f"exec {shlex.quote(sys.executable)} {shlex.quote(daemon)} "
        f"health collect --timeout 6 --max-misses 2 "
        f">> {shlex.quote(JOB_LOG)} 2>&1\n"
    )


def schedule_install(period_min=15.0, persisted=True, charging=False):
    """Write the collector wrapper and register it with Android's JobScheduler."""
    _need_scheduler()
    os.makedirs(JOB_DIR, exist_ok=True)
    with open(JOB_SCRIPT, "w") as fh:
        fh.write(_job_script_body())
    os.chmod(JOB_SCRIPT, 0o700)
    period_ms = max(900_000, int(period_min * 60_000))  # Android's 15-min floor
    subprocess.run(
        ["termux-job-scheduler", "--script", JOB_SCRIPT,
         "--job-id", str(JOB_ID), "--period-ms", str(period_ms),
         "--battery-not-low", "true",
         "--persisted", "true" if persisted else "false",
         "--charging", "true" if charging else "false"],
        check=True)
    return {"job_id": JOB_ID, "script": JOB_SCRIPT, "log": JOB_LOG,
            "period_min": period_ms / 60000, "persisted": persisted,
            "charging": charging}


def schedule_status():
    _need_scheduler()
    out = subprocess.run(["termux-job-scheduler", "--pending"],
                         capture_output=True, text=True)
    return {"job_id": JOB_ID, "script": JOB_SCRIPT, "log": JOB_LOG,
            "script_exists": os.path.exists(JOB_SCRIPT),
            "pending": out.stdout.strip() or out.stderr.strip()}


def schedule_remove():
    _need_scheduler()
    subprocess.run(["termux-job-scheduler", "--cancel", "--job-id", str(JOB_ID)],
                   check=False)
    return {"job_id": JOB_ID, "cancelled": True}
